set_project("omasnap")
set_installdir(os.getenv("HOME") .. "/.local")
local version = "1.21.0"
set_version(version)

set_languages("c++23")
add_rules("mode.release", "mode.debug")
add_cxflags("-Wall", "-Wextra", "-Wpedantic")

add_requires("wayland-client", {system = true})
add_requires("libdeflate", {system = true})

-- wayland-scanner generates the client headers and code for the protocol XMLs.
rule("wayland-protocols")
    set_extensions(".xml")
    after_load(function (target)
        local gendir = path.join(target:autogendir(), "wayland")
        target:add("includedirs", gendir, {public = true})
        local sourcebatch = target:sourcebatches()["wayland-protocols"]
        for _, sourcefile in ipairs(sourcebatch.sourcefiles) do
            local code = path.join(gendir, path.basename(sourcefile) .. "-protocol.c")
            table.insert(target:objectfiles(), target:objectfile(code))
        end
    end)
    on_preparecmd_file(function (target, batchcmds, sourcefile, opt)
        import("lib.detect.find_tool")
        local scanner = assert(find_tool("wayland-scanner", {norun = true}), "wayland-scanner not found!")
        local gendir = path.join(target:autogendir(), "wayland")
        local name = path.basename(sourcefile)
        local header = path.join(gendir, name .. "-client-protocol.h")
        local code = path.join(gendir, name .. "-protocol.c")
        batchcmds:show_progress(opt.progress, "${color.build.object}generating.wayland %s", name)
        batchcmds:mkdir(gendir)
        batchcmds:vrunv(scanner.program, {"client-header", path(sourcefile), path(header)})
        batchcmds:vrunv(scanner.program, {"private-code", path(sourcefile), path(code)})
        batchcmds:add_depfiles(sourcefile)
        batchcmds:set_depcache(target:dependfile(code))
        batchcmds:set_depmtime(math.max(os.mtime(header), os.mtime(code)))
    end)
    on_buildcmd_file(function (target, batchcmds, sourcefile, opt)
        local gendir = path.join(target:autogendir(), "wayland")
        local name = path.basename(sourcefile)
        local code = path.join(gendir, name .. "-protocol.c")
        local objectfile = target:objectfile(code)
        batchcmds:show_progress(opt.progress, "${color.build.object}compiling.wayland %s", name)
        batchcmds:compile(code, objectfile, {configs = {includedirs = gendir}})
        batchcmds:add_depfiles(sourcefile, code)
        batchcmds:set_depcache(target:dependfile(objectfile))
        batchcmds:set_depmtime(os.mtime(objectfile))
    end)

target("omasnap-core")
    set_kind("static")
    set_targetdir("$(builddir)")
    on_install(function (target) end)
    add_rules("qt.static", "wayland-protocols")
    add_files("src/*.cpp|main.cpp|pin.cpp|stitch-replay.cpp")
    add_files("src/*.hpp")
    add_files(
        "protocols/wlr-virtual-pointer-unstable-v1.xml",
        "/usr/share/wayland-protocols/staging/ext-foreign-toplevel-list/ext-foreign-toplevel-list-v1.xml",
        "/usr/share/wayland-protocols/staging/ext-image-capture-source/ext-image-capture-source-v1.xml",
        "/usr/share/wayland-protocols/staging/ext-image-copy-capture/ext-image-copy-capture-v1.xml")
    add_includedirs("src", {public = true})
    add_frameworks("QtConcurrent", "QtGui", "QtWidgets", {public = true})
    add_syslinks("LayerShellQtInterface", {public = true})
    add_packages("wayland-client", "libdeflate", {public = true})

target("omasnap")
    set_targetdir("$(builddir)")
    add_rules("qt.widgetapp")
    add_files("src/main.cpp", "src/pin.cpp")
    add_deps("omasnap-core")
    add_defines('OMASNAP_VERSION="' .. version .. '"')
    add_installfiles("omasnap.desktop", {prefixdir = "share/applications"})
    add_installfiles("assets/Lucide-ISC.txt", {prefixdir = "share/licenses/omasnap"})

target("omasnap-smoke")
    set_targetdir("$(builddir)")
    on_install(function (target) end)
    add_rules("qt.console")
    add_files("tests/*.cpp")
    add_files("src/cli-path.cpp", "src/recent-snaps.cpp", "src/capture.cpp", "src/overlay-chrome.cpp",
        "src/stitch.cpp", "src/auto-capture.cpp")
    add_deps("omasnap-core")
    add_includedirs("tests")
    add_frameworks("QtConcurrent", "QtGui", "QtTest", "QtWidgets")

target("stitch-replay")
    set_targetdir("$(builddir)")
    on_install(function (target) end)
    add_rules("qt.console")
    add_files("src/stitch-replay.cpp", "src/stitch.cpp")
    add_includedirs("src")
    add_frameworks("QtGui")
